version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    command: ["apache2-foreground"]  # Use for PHP apps

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctf_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
